### ISSUE TITLE
Migrate JIRA issues to GitHub issues

### ISSUE THREAD

**Issue by tjdav** [dooksajs/dooksa#1]
It would be nice to migrate all Jira issues to GitHub Issues to preserve the history

I found this after briefly looking around for solutions, not sure if it's still relevant
https://gist.github.com/jonmagic/5282384165e0f86ef105

**Comment by ajdavid** [comment]
There is this resource/scripts, No idea if it still works https://github.com/benwinding/jira-to-github

Apache Arrow documented the process, relatively recently, in this [GitHub Issue ](https://github.com/apache/arrow/issues/14542)

**Comment by ajdavid** [comment]
JIra Issues for Dooksa Project exported

**Comment by tjdav** [comment]
Alternatively, we can start fresh and manually transfer over things of importance, what do you think?

**Comment by ajdavid** [comment]
Should this still be open?. The Jira Issues might need to be curated for historical purposes. Not a high priority.
